spring:
  cloud:
    zookeeper:
      enabled: true
      connect-string: 127.0.0.1:2181
  application:
    name: dubbo-demo-consume
  main:
    allow-bean-definition-overriding: true

server:
  port: 8089

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: dubbo-demo-provider
  consumer:
    check: false
